name: Publish
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master   
jobs:
  msys2-mingw64:
    name: Publish for MinGW 64
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3    
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: dos2unix mingw-w64-x86_64-gcc automake autoconf make git
      - name: CI-Build
        run: |
          dos2unix PKGBUILD.mingw
          makepkg BUILDDIR=/tmp/pkg -f -p PKGBUILD.mingw
      - uses: ncipollo/release-action@v1
        with:
          name: Latest
          tag: "1.0"
          artifacts: "*.pkg.tar.zst"
          allowUpdates: true
          commit: true
          draft: false
          makeLatest: true
          omitBody: true
          omitPrereleaseDuringUpdate: true
          replacesArtifacts: true
