name: Publish
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master   
jobs:
  msys2-mingw64:
    name: Publish for MinGW 64
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: dos2unix mingw-w64-x86_64-gcc automake autoconf make git
      - name: CI-Build
        run: makepkg -f BUILDDIR=.buildpkg -p PKGBUILD.mingw
      - uses: ncipollo/release-action@v1
        with:
          tag: 1.0
          artifacts: "*.pkg.tar.zst"
          allowUpdates: true
          draft: false
          makeLatest: true
          omitBody: true
          omitPrereleaseDuringUpdate: true
          replacesArtifacts: true
